#!/opt/bin/perl

use utf8;
use warnings;
use strict;
use lib "$ENV{LAMBDA_TASK_ROOT}/local/lib/perl5";
use Furl;
use JSON;

my $furl = Furl->new;
my ($handler, $function) = split /\./, $ENV{_HANDLER}, 2;
require "$ENV{LAMBDA_TASK_ROOT}/$handler.pl";
my $func = \&$function;

while(1) {
    my $res = $furl->get("http://$ENV{AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/next");
    die $res->status_line unless $res->is_success;
    my $req_id = $res->header("Lambda-Runtime-Aws-Request-Id");
    my $event = decode_json($res->content);
    my $result = $func->($event);
    $furl->post(
        "http://$ENV{AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/$req_id/response",
        [],
        encode_json($result),
    );
}

1;
